- task: UseNode@1
  inputs:
- task: Npm@1
  inputs:
    command: 'install'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install -g @angular/cli'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'