- task: UseNode@0
  inputs:
   #versionSpec: '10.x' 
- task: Npm@1
  inputs:
    command: 'install'
- task: Npm@2
  inputs:
    command: 'custom'
    customCommand: 'install -g @angular/cli'
- task: Npm@3
  inputs:
    command: 'custom'
    customCommand: 'run build'